#!/bin/bash

#############################################################################
#
# settings
#

DATA_DIR=/var/www/html/gratia-summary-generic/data

BASE_URL="http://gratiaweb.grid.iu.edu/gratia"
VO="osg|OSG"
SUBMIT_HOST_PROBE="osg-xsede.grid.iu.edu"
GLIDEIN_USER="xsede-pilot"

#############################################################################

START_DATE_YEAR=`date --utc -d "last year" +"%Y-%m-%d"`
START_DATE_MONTH=`date --utc -d "last month" +"%Y-%m-%d"`
START_DATE_WEEK=`date --utc -d "last week" +"%Y-%m-%d"`
END_DATE=`date --utc +"%Y-%m-%d"`

READABLE_DATE=`TZ=America/Chicago /bin/date`

echo "Downloading data for $START_DATE_YEAR to $END_DATE"

cd $DATA_DIR

function include_graph()
{
    description=$1
    filename=$2
    query_url=$3
    graph_url=$4


    wget -q -O $filename "$graph_url"
    if [ $? != 0 ]; then
        echo "FAILED: $graph_url"
        cp ../nodata_text.png $filename
    fi

    cat >>index.html.new <<EOF
  <tr>
    <td>
      <img src='data/$filename'>
    </td>
    <td>
      $description 
      <p>
      <a href='$query_url'>Interactive Query</a>
    </td>
  </tr>
EOF
}


cat >index.html.new <<EOF
<html>
  <head>
    <title>Gratia Summary Graphs</title>
  </head>
<body>
<p>Last update: $READABLE_DATE</p>
<table cellspacing="5" cellpadding="5" border="0">
EOF

include_graph \
   "Hours By Project reported by Gratia" \
   "daily_hours_by_project.png" \
   "$BASE_URL/xml/project_hours_bar?facility=.*&probe=$SUBMIT_HOST_PROBE&resource-type=BatchPilot&vo=.*&grid=.*&user=.*&endtime=$END_DATE+23%3A59%3A59&exclude-vo=unknown%7Cother&includeFailed=true&exclude-role=NONE&span=86400&role=.*&starttime=$START_DATE_WEEK+00%3A00%3A00&exclude-facility=NONE&exclude-user=NONE&includeSuccess=true" \
   "$BASE_URL/bar_graphs/project_hours_bar?facility=.*&probe=$SUBMIT_HOST_PROBE&resource-type=BatchPilot&vo=.*&grid=.*&user=.*&endtime=$END_DATE+23%3A59%3A59&exclude-vo=unknown%7Cother&includeFailed=true&exclude-role=NONE&span=86400&role=.*&starttime=$START_DATE_WEEK+00%3A00%3A00&exclude-facility=NONE&exclude-user=NONE&includeSuccess=true" \

include_graph \
   "Hours By Users reported by Gratia" \
   "daily_hours_by_user.png" \
   "$BASE_URL/xml/glidein_dn_hours_bar?facility=.*&probe=$SUBMIT_HOST_PROBE&resource-type=BatchPilot&vo=.*&grid=.*&user=.*&endtime=$END_DATE+23%3A59%3A59&exclude-vo=unknown%7Cother&includeFailed=true&exclude-role=NONE&span=86400&role=.*&starttime=$START_DATE_WEEK+00%3A00%3A00&exclude-facility=NONE&exclude-user=NONE&includeSuccess=true" \
   "$BASE_URL/glidein_bar_graphs/glidein_dn_hours_bar?facility=.*&probe=$SUBMIT_HOST_PROBE&resource-type=BatchPilot&vo=.*&grid=.*&user=.*&endtime=$END_DATE+23%3A59%3A59&exclude-vo=unknown%7Cother&includeFailed=true&exclude-role=NONE&span=86400&role=.*&starttime=$START_DATE_WEEK+00%3A00%3A00&exclude-facility=NONE&exclude-user=NONE&includeSuccess=true" \

include_graph \
   "User exit codes as captured by Condor" \
   "exit_codes.png" \
   "$BASE_URL/xml/glidein_exitcode_bar?facility=.*&probe=$SUBMIT_HOST_PROBE&resource-type=BatchPilot&vo=.*&grid=.*&user=.*&endtime=$END_DATE+23%3A59%3A59&exclude-vo=unknown%7Cother&includeFailed=true&exclude-role=NONE&span=86400&role=.*&starttime=$START_DATE_WEEK+00%3A00%3A00&exclude-facility=NONE&exclude-user=NONE&includeSuccess=true" \
   "$BASE_URL/glidein_bar_graphs/glidein_exitcode_bar?facility=.*&probe=$SUBMIT_HOST_PROBE&resource-type=BatchPilot&vo=.*&grid=.*&user=.*&endtime=$END_DATE+23%3A59%3A59&exclude-vo=unknown%7Cother&includeFailed=true&exclude-role=NONE&span=86400&role=.*&starttime=$START_DATE_WEEK+00%3A00%3A00&exclude-facility=NONE&exclude-user=NONE&includeSuccess=true"

include_graph \
   "Daily Hours by Site, used by the GlideinWMS glideins, across sites" \
   "daily_hours_by_site.png" \
   "$BASE_URL/xml/dn_site_hours_bar?endtime=$END_DATE+23%3A59%3A59&span=86400&facility=.*&probe=.*&resource-type=%5EBatch%24&vo=$VO&role=.*&user=$GLIDEIN_USER&starttime=$START_DATE_WEEK+00%3A00%3A00&exclude-facility=NONE%7CGeneric%7CObsolete&exclude-user=NONE&includeSuccess=true&exclude-vo=unknown%7Cother&includeFailed=true&exclude-role=NONE" \
   "$BASE_URL/bar_graphs/dn_site_hours_bar?endtime=$END_DATE+23%3A59%3A59&span=86400&facility=.*&probe=.*&resource-type=%5EBatch%24&vo=$VO&role=.*&user=$GLIDEIN_USER&starttime=$START_DATE_WEEK+00%3A00%3A00&exclude-facility=NONE%7CGeneric%7CObsolete&exclude-user=NONE&includeSuccess=true&exclude-vo=unknown%7Cother&includeFailed=true&exclude-role=NONE"

include_graph \
   "Cumulative Hours by Site, added up by site, over a month" \
   "cumulative_hours_by_site.png" \
   "$BASE_URL/xml/facility_success_cumulative_smry?span=86400&facility=.*&probe=.*&resource-type=%5EBatch%24&vo=.*&user=$GLIDEIN_USER&starttime=$START_DATE_MONTH+00%3A00%3A00&exclude-facility=NONE%7CGeneric%7CObsolete&exclude-user=NONE&endtime=$END_DATE+23%3A59%3A59&exclude-vo=unknown%7Cother" \
   "http://gratiaweb.grid.iu.edu/gratia/cumulative_graphs/facility_success_cumulative_smry?span=86400&facility=.*&probe=.*&resource-type=^Batch$&vo=.*&user=$GLIDEIN_USER&starttime=$START_DATE_MONTH%2000:00:00&exclude-facility=NONE|Generic|Obsolete&exclude-user=NONE&endtime=$END_DATE%2023:59:59&exclude-vo=unknown|other&"



echo >>index.html.new <<EOF
</table>
</body>
</html>
EOF
mv index.html.new ../index.html

